[package]
name = "ree-lending-demo-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.17"
ic-cdk-macros = "0.17"
thiserror = "1"
serde = { version = "1.0", features = ["derive"] }
hex = "0.4"
ic-stable-structures = "0.6"
ciborium = "0.2"
ree-types = { git =  "https://github.com/octopus-network/ree-types.git", rev = "1bc6810a7aac2576c32bdca26b6dd399b1a307eb" }
serde_json = "1.0"
